
---
- name: Generate
  hosts: all
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/Backups_Exos.git
          run_once: true
          delegate_to: localhost

        - name: List letencrypt certificate directory
          command: ls -rt1 /tmp/Backups_Exos/
          register: certificates

        - name: Debug latest file
          ansible.builtin.debug:
            msg: "The latest configuration file is {{certificates.stdout_lines[0]}}/{{inventory_hostname}}.txt"

        - name: Restore configuration
          community.network.exos_config:           
            src: /tmp/Backups_Exos/{{ certificates.stdout_lines[0] }}/sw1.txt
            diff_against: running
            save_when: modified
