
---
- name: Generate
  hosts: all
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/Backups_Exos.git
          run_once: true
          delegate_to: localhost

        - name: git init and add origin 
          ignore_errors: true
          shell: "{{ item }}"
          args: 
            chdir: /tmp/Backups_Exos
          loop: 
            - ls -Art | grep '/' | tail -n 1
          register: latest_directory
          delegate_to: localhost
          run_once: true
 
        - name: Restore configuration
          community.network.exos_config:
            replace: 
              src: /tmp/Backups_Exos/{{latest_directory}}/sw1.txt
            save_when: modified
