
---
- name: Generate
  hosts: all
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/Backups_Exos.git
          run_once: true
          delegate_to: localhost

        - name: Restore configuration
          community.network.exos_config:
            src: /tmp/Backups_Exos/2024_03_14@14_45_29/sw1.txt
            replace: block
            save_when: modified

