
---
- name: Generate
  hosts: all
  connection: network_cli
  gather_facts: false
  
  collections:
    - community.network




  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/Backups_Exos.git

          run_once: true
          delegate_to: localhost

    - name: Get files in a folder
      ansible.builtin.find:
        paths: "/tmp/Backups_Exos"
        file_type: directory
      register: found_files

    - name: Get latest file
      set_fact:
        latest_file: "{{ (found_files.files | sort(attribute='mtime') | last).path }}"

    - name: Debug latest file
      ansible.builtin.debug:
        msg: "The latest configuration file is {{ latest_file }}"

    - name: Restore configuration on EXOS switch
      community.network.exos_config:
        src: "{{ latest_file }}/sw1.txt"
        diff_against: running
        save_when: modified
