
---
- name: Generate
  hosts: all
  connection: network_cli
  gather_facts: false
  vars_files:
    - secret4.yml
  
  collections:
    - community.network


  tasks:
    - name: Create a file new3_file.txt and push to GitHub
      block:
        - name: Clone the existing GitHub repository
          args: 
            chdir: /tmp
          command: git clone https://github.com/shezanhossain2/Backups_Exos/.git
          run_once: true
          delegate_to: localhost

        - name: Restore IOS-XE configuration
          ansible.netcommon.cli_restore:
            filename: /tmp/Backups_Exos/2024_05_12@19_55_21/sw1.cfg
            path: flash://
            when: inventory_hostname == 'sw1'